package com.beyon.identity.enums;

public enum AccountStatus {
    PENDING_VERIFICATION,
    PENDING_SUPER_ADMIN_VERIFICATION,
    APPROVED,
    ACTIVE,
    SUSPENDED,
    DEACTIVATED,
    INCOMPLETE,
    COMPLETED,
    PENDING_INSTITUTION_VERIFICATION,
    PENDING_COMPANY_VERIFICATION,
    REJECTED
}
