spring:
  jackson:
    default-property-inclusion: non_null

aws:
  endpoint-url: ${AWS_ENDPOINT_URL:http://localhost:4566}
  region: ${AWS_REGION:us-east-1}
  access-key-id: ${AWS_ACCESS_KEY_ID:test}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:test}
